"""make financial metrics nullable

Revision ID: 11cf340c0a6c
Revises: 8c781f762a7a
Create Date: 2026-09-20 14:40:47.816707

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "11cf340c0a6c"
down_revision: str | Sequence[str] | None = "8c781f762a7a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("financial_metrics", "revenue", existing_type=sa.NUMERIC(precision=20, scale=2), nullable=True)
    op.alter_column(
        "financial_metrics", "operating_income", existing_type=sa.NUMERIC(precision=20, scale=2), nullable=True
    )
    op.alter_column("financial_metrics", "net_income", existing_type=sa.NUMERIC(precision=20, scale=2), nullable=True)
    op.alter_column("financial_metrics", "total_assets", existing_type=sa.NUMERIC(precision=20, scale=2), nullable=True)
    op.alter_column(
        "financial_metrics", "total_liabilities", existing_type=sa.NUMERIC(precision=20, scale=2), nullable=True
    )
    op.alter_column(
        "financial_metrics", "stockholders_equity", existing_type=sa.NUMERIC(precision=20, scale=2), nullable=True
    )
    op.alter_column(
        "financial_metrics", "current_assets", existing_type=sa.NUMERIC(precision=20, scale=2), nullable=True
    )
    op.alter_column(
        "financial_metrics", "operating_cash_flow", existing_type=sa.NUMERIC(precision=20, scale=2), nullable=True
    )
    op.alter_column(
        "financial_metrics", "capital_expenditures", existing_type=sa.NUMERIC(precision=20, scale=2), nullable=True
    )
    op.alter_column(
        "financial_metrics", "free_cash_flow", existing_type=sa.NUMERIC(precision=20, scale=2), nullable=True
    )
    op.alter_column(
        "financial_metrics", "shares_outstanding", existing_type=sa.NUMERIC(precision=20, scale=2), nullable=True
    )
    op.alter_column(
        "financial_metrics",
        "shares_outstanding_diluted",
        existing_type=sa.NUMERIC(precision=20, scale=2),
        nullable=True,
    )
    op.alter_column(
        "financial_metrics", "current_ratio", existing_type=sa.NUMERIC(precision=20, scale=2), nullable=True
    )
    op.alter_column(
        "financial_metrics", "debt_to_assets_ratio", existing_type=sa.NUMERIC(precision=20, scale=2), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "financial_metrics", "debt_to_assets_ratio", existing_type=sa.NUMERIC(precision=20, scale=2), nullable=False
    )
    op.alter_column(
        "financial_metrics", "current_ratio", existing_type=sa.NUMERIC(precision=20, scale=2), nullable=False
    )
    op.alter_column(
        "financial_metrics",
        "shares_outstanding_diluted",
        existing_type=sa.NUMERIC(precision=20, scale=2),
        nullable=False,
    )
    op.alter_column(
        "financial_metrics", "shares_outstanding", existing_type=sa.NUMERIC(precision=20, scale=2), nullable=False
    )
    op.alter_column(
        "financial_metrics", "free_cash_flow", existing_type=sa.NUMERIC(precision=20, scale=2), nullable=False
    )
    op.alter_column(
        "financial_metrics", "capital_expenditures", existing_type=sa.NUMERIC(precision=20, scale=2), nullable=False
    )
    op.alter_column(
        "financial_metrics", "operating_cash_flow", existing_type=sa.NUMERIC(precision=20, scale=2), nullable=False
    )
    op.alter_column(
        "financial_metrics", "current_assets", existing_type=sa.NUMERIC(precision=20, scale=2), nullable=False
    )
    op.alter_column(
        "financial_metrics", "stockholders_equity", existing_type=sa.NUMERIC(precision=20, scale=2), nullable=False
    )
    op.alter_column(
        "financial_metrics", "total_liabilities", existing_type=sa.NUMERIC(precision=20, scale=2), nullable=False
    )
    op.alter_column(
        "financial_metrics", "total_assets", existing_type=sa.NUMERIC(precision=20, scale=2), nullable=False
    )
    op.alter_column("financial_metrics", "net_income", existing_type=sa.NUMERIC(precision=20, scale=2), nullable=False)
    op.alter_column(
        "financial_metrics", "operating_income", existing_type=sa.NUMERIC(precision=20, scale=2), nullable=False
    )
    op.alter_column("financial_metrics", "revenue", existing_type=sa.NUMERIC(precision=20, scale=2), nullable=False)
    # ### end Alembic commands ###
