"""document_accessioner_number

Revision ID: 250a7aba7333
Revises: bc796de94dd5
Create Date: 2026-08-16 01:13:00.757593

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "250a7aba7333"
down_revision: str | Sequence[str] | None = "bc796de94dd5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("accession_number", sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "accession_number")
    # ### end Alembic commands ###
