"""document_datetime_to_date2

Revision ID: 2cc9fcd12f00
Revises: a6d550f8bcf0
Create Date: 2026-08-16 23:38:48.683434

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2cc9fcd12f00"
down_revision: str | Sequence[str] | None = "a6d550f8bcf0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "documents", "filing_date", existing_type=postgresql.TIMESTAMP(), type_=sa.Date(), existing_nullable=False
    )
    op.alter_column(
        "documents", "period_of_report", existing_type=postgresql.TIMESTAMP(), type_=sa.Date(), existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "documents", "period_of_report", existing_type=sa.Date(), type_=postgresql.TIMESTAMP(), existing_nullable=False
    )
    op.alter_column(
        "documents", "filing_date", existing_type=sa.Date(), type_=postgresql.TIMESTAMP(), existing_nullable=False
    )
    # ### end Alembic commands ###
