"""make CIK non-nullable

Revision ID: 3417b936f86b
Revises: 7b8d2c4f91a1
Create Date: 2026-08-13 22:42:50.189900

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3417b936f86b"
down_revision: str | Sequence[str] | None = "7b8d2c4f91a1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("companies", "CIK", existing_type=sa.VARCHAR(length=255), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("companies", "CIK", existing_type=sa.VARCHAR(length=255), nullable=True)
    # ### end Alembic commands ###
