"""financial metrics

Revision ID: 8c781f762a7a
Revises: 2cc9fcd12f00
Create Date: 2026-08-24 23:33:13.025393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c781f762a7a'
down_revision: Union[str, Sequence[str], None] = '2cc9fcd12f00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_metrics', sa.Column('revenue', sa.Numeric(precision=20, scale=2), nullable=False))
    op.add_column('financial_metrics', sa.Column('operating_income', sa.Numeric(precision=20, scale=2), nullable=False))
    op.add_column('financial_metrics', sa.Column('net_income', sa.Numeric(precision=20, scale=2), nullable=False))
    op.add_column('financial_metrics', sa.Column('total_assets', sa.Numeric(precision=20, scale=2), nullable=False))
    op.add_column('financial_metrics', sa.Column('total_liabilities', sa.Numeric(precision=20, scale=2), nullable=False))
    op.add_column('financial_metrics', sa.Column('stockholders_equity', sa.Numeric(precision=20, scale=2), nullable=False))
    op.add_column('financial_metrics', sa.Column('current_assets', sa.Numeric(precision=20, scale=2), nullable=False))
    op.add_column('financial_metrics', sa.Column('operating_cash_flow', sa.Numeric(precision=20, scale=2), nullable=False))
    op.add_column('financial_metrics', sa.Column('capital_expenditures', sa.Numeric(precision=20, scale=2), nullable=False))
    op.add_column('financial_metrics', sa.Column('free_cash_flow', sa.Numeric(precision=20, scale=2), nullable=False))
    op.add_column('financial_metrics', sa.Column('shares_outstanding', sa.Numeric(precision=20, scale=2), nullable=False))
    op.add_column('financial_metrics', sa.Column('shares_outstanding_diluted', sa.Numeric(precision=20, scale=2), nullable=False))
    op.add_column('financial_metrics', sa.Column('current_ratio', sa.Numeric(precision=20, scale=2), nullable=False))
    op.add_column('financial_metrics', sa.Column('debt_to_assets_ratio', sa.Numeric(precision=20, scale=2), nullable=False))
    op.alter_column('financial_metrics', 'period',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.drop_column('financial_metrics', 'metric_name')
    op.drop_column('financial_metrics', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_metrics', sa.Column('value', sa.NUMERIC(precision=24, scale=6), autoincrement=False, nullable=False))
    op.add_column('financial_metrics', sa.Column('metric_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.alter_column('financial_metrics', 'period',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.drop_column('financial_metrics', 'debt_to_assets_ratio')
    op.drop_column('financial_metrics', 'current_ratio')
    op.drop_column('financial_metrics', 'shares_outstanding_diluted')
    op.drop_column('financial_metrics', 'shares_outstanding')
    op.drop_column('financial_metrics', 'free_cash_flow')
    op.drop_column('financial_metrics', 'capital_expenditures')
    op.drop_column('financial_metrics', 'operating_cash_flow')
    op.drop_column('financial_metrics', 'current_assets')
    op.drop_column('financial_metrics', 'stockholders_equity')
    op.drop_column('financial_metrics', 'total_liabilities')
    op.drop_column('financial_metrics', 'total_assets')
    op.drop_column('financial_metrics', 'net_income')
    op.drop_column('financial_metrics', 'operating_income')
    op.drop_column('financial_metrics', 'revenue')
    # ### end Alembic commands ###
