"""document_datetime_to_date

Revision ID: a6d550f8bcf0
Revises: d8de615ec337
Create Date: 2026-08-16 23:35:23.839135

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "a6d550f8bcf0"
down_revision: str | Sequence[str] | None = "d8de615ec337"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
