"""document

Revision ID: bc796de94dd5
Revises: 3417b936f86b
Create Date: 2026-08-16 00:26:02.819806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc796de94dd5'
down_revision: Union[str, Sequence[str], None] = '3417b936f86b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('year', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('quarter', sa.Integer(), nullable=False))
    op.drop_column('documents', 'source_url')
    op.drop_column('documents', 'published_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('source_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('documents', 'quarter')
    op.drop_column('documents', 'year')
    # ### end Alembic commands ###
