"""document_period_of_report

Revision ID: d8de615ec337
Revises: 250a7aba7333
Create Date: 2026-08-16 23:24:57.735850

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d8de615ec337"
down_revision: str | Sequence[str] | None = "250a7aba7333"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("filing_date", sa.DateTime(), nullable=False))
    op.add_column("documents", sa.Column("period_of_report", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "period_of_report")
    op.drop_column("documents", "filing_date")
    # ### end Alembic commands ###
