from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any

from sqlalchemy.orm import Session

from financial_data_agent.constants import SQL_ROW_LIMIT, SQL_STATEMENT_TIMEOUT_MS, SQL_WRITE_KEYWORDS

LITERAL_OR_COMMENT_PATTERN = re.compile(r"'(?:[^']|'')*'|\"(?:[^\"]|\"\")*\"|--[^\n]*|/\*.*?\*/", re.DOTALL)
WRITE_KEYWORD_PATTERN = re.compile(rf"\b({'|'.join(SQL_WRITE_KEYWORDS)})\b", re.IGNORECASE)
READ_STATEMENT_PATTERN = re.compile(r"^\s*\(*\s*(select|with)\b", re.IGNORECASE)


class UnsafeSQLError(Exception):
    """Raised when generated SQL is not a single read-only query."""


@dataclass(frozen=True, slots=True)
class SQLQueryResult:
    """Rows returned by a read-only query."""

    columns: list[str]
    rows: list[tuple[Any, ...]]
    truncated: bool


def _mask_literal_or_comment(match: re.Match[str]) -> str:
    """Replace a string literal, quoted identifier or comment with an inert placeholder.

    Args:
        match: The matched literal, identifier or comment.

    Returns:
        An empty literal or identifier of the same kind, or a space for a comment.
    """
    token = match.group(0)
    if token[0] in "'\"":
        return token[0] * 2
    return " "


def guard_select_sql(sql: str) -> str:
    """Reject SQL that is not a single SELECT statement.

    Literals, quoted identifiers and comments are masked before scanning, so keywords inside
    them neither trigger nor hide a rejection. This is defence in depth; the read-only
    transaction is the actual enforcement.

    Args:
        sql: The SQL generated by the model.

    Returns:
        The original SQL, unchanged.

    Raises:
        UnsafeSQLError: If the SQL is empty, has several statements, is not a SELECT, or contains a write keyword.
    """
    masked = LITERAL_OR_COMMENT_PATTERN.sub(_mask_literal_or_comment, sql).strip().rstrip(";")
    if not masked.strip():
        raise UnsafeSQLError("SQL is empty")
    if ";" in masked:
        raise UnsafeSQLError("Only a single statement is allowed")
    if not READ_STATEMENT_PATTERN.match(masked):
        raise UnsafeSQLError("Only SELECT queries are allowed")
    keyword = WRITE_KEYWORD_PATTERN.search(masked)
    if keyword:
        raise UnsafeSQLError(f"Keyword {keyword.group(1).upper()} is not allowed in a read-only query")
    return sql


def execute_readonly_sql(
    session: Session,
    sql: str,
    row_limit: int = SQL_ROW_LIMIT,
    timeout_ms: int = SQL_STATEMENT_TIMEOUT_MS,
) -> SQLQueryResult:
    """Guard and execute generated SQL, returning at most `row_limit` rows.

    The session must come from `get_readonly_session_factory()`. The transaction is always
    rolled back so the pooled connection is returned clean.

    Args:
        session: A read-only database session.
        sql: The SQL generated by the model.
        row_limit: Maximum number of rows to return.
        timeout_ms: Statement timeout in milliseconds, applied on PostgreSQL.

    Returns:
        The column names, up to `row_limit` rows, and whether more rows were available.

    Raises:
        UnsafeSQLError: If the SQL fails the guard.
    """
    guarded = guard_select_sql(sql)
    try:
        connection = session.connection()
        if connection.dialect.name == "postgresql":
            connection.exec_driver_sql(f"SET LOCAL statement_timeout = {int(timeout_ms)}")
        result = connection.exec_driver_sql(guarded, execution_options={"no_parameters": True})
        rows = result.fetchmany(row_limit + 1)
        return SQLQueryResult(
            columns=list(result.keys()),
            rows=[tuple(row) for row in rows[:row_limit]],
            truncated=len(rows) > row_limit,
        )
    finally:
        session.rollback()
