from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from sqlalchemy.orm import Session

from financial_data_agent.constants import SQL_ROW_LIMIT, SQL_STATEMENT_TIMEOUT_MS


@dataclass(frozen=True, slots=True)
class SQLQueryResult:
    """Rows returned by a model-generated query."""

    columns: list[str]
    rows: list[tuple[Any, ...]]
    truncated: bool


def execute_llm_sql(
    session: Session,
    sql: str,
    row_limit: int = SQL_ROW_LIMIT,
    timeout_ms: int = SQL_STATEMENT_TIMEOUT_MS,
) -> SQLQueryResult:
    """Execute model-generated SQL, returning at most `row_limit` rows.

    The session must come from `get_llm_reader_session_factory()`; the `llm_reader` role's
    grants are what keep the query read-only. The transaction is always rolled back so the
    pooled connection is returned clean.

    Args:
        session: A session logged in as `llm_reader`.
        sql: The SQL generated by the model, sent to the driver verbatim.
        row_limit: Maximum number of rows to return.
        timeout_ms: Statement timeout in milliseconds, applied on PostgreSQL.

    Returns:
        The column names, up to `row_limit` rows, and whether more rows were available.
    """
    try:
        connection = session.connection()
        if connection.dialect.name == "postgresql":
            connection.exec_driver_sql(f"SET LOCAL statement_timeout = {int(timeout_ms)}")
        result = connection.exec_driver_sql(sql, execution_options={"no_parameters": True})
        rows = result.fetchmany(row_limit + 1)
        return SQLQueryResult(
            columns=list(result.keys()),
            rows=[tuple(row) for row in rows[:row_limit]],
            truncated=len(rows) > row_limit,
        )
    finally:
        session.rollback()
